#!/usr/bin/env bash

# Enable color
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Pass correct shell to tmux (needed for Omarchy)
set-option -g default-shell "$SHELL"

# Pass terminal titles through tmux
set -g set-titles on
set -g set-titles-string "#T"

# Enable mouse compatibility
set -g mouse on

# Enable tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Themes
set -g @plugin 'hnielsen123/monochrome-night-tmux'
set -g @monochrome-night-tmux_show_netspeed 0
set -g @monochrome-night-tmux_show_ip 1
set -g @monochrome-night-tmux_network_iface_mode tun_only

# Navigate windows using shift left and right or alt+h and alt+l
bind -n S-Left  previous-window
bind -n S-Right next-window
bind -n M-h previous-window
bind -n M-l next-window

# Navigate sessions using option left and right
bind -n M-Left  switch-client -p
bind -n M-Right switch-client -n

# Move between panes with vim keys
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Kill panes and windows without confirmation
bind x kill-pane
bind & kill-window

# New panes with vim keys
bind C-l split-window -h
bind C-j split-window -v

# Let escape exit copy mode in emacs binding mode
bind -T copy-mode Escape send-keys -X cancel

run '~/.tmux/plugins/tpm/tpm'
